import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React, { useState } from 'react';
import { Layers, BookOpen, Plus, Users, Trash2, UserCheck } from 'lucide-react';
export const BatchesCoursesView = ({ batches, courses, userRole, onOpenAddBatchModal, onOpenAddCourseModal, onDeleteBatch }) => {
    const [activeSubTab, setActiveSubTab] = useState('batches');
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-3 border-b border-[#222222]", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-3xl font-black italic tracking-tight uppercase text-white", children: "Cohorts & Curriculum" }), _jsx("p", { className: "text-xs font-mono text-gray-500 mt-0.5 uppercase tracking-wider", children: "Academic batch rosters, course offerings, credit allocations, and assigned advisors" })] }), _jsxs("div", { className: "flex items-center gap-1 bg-[#181818] p-1 rounded-sm border border-[#222222]", children: [_jsxs("button", { onClick: () => setActiveSubTab('batches'), className: `flex items-center gap-2 px-3.5 py-1.5 rounded-sm text-xs font-bold uppercase transition-all ${activeSubTab === 'batches'
                                    ? 'bg-white text-black font-black'
                                    : 'text-gray-400 hover:text-white'}`, children: [_jsx(Layers, { className: "w-3.5 h-3.5" }), "Batches (", batches.length, ")"] }), _jsxs("button", { onClick: () => setActiveSubTab('courses'), className: `flex items-center gap-2 px-3.5 py-1.5 rounded-sm text-xs font-bold uppercase transition-all ${activeSubTab === 'courses'
                                    ? 'bg-white text-black font-black'
                                    : 'text-gray-400 hover:text-white'}`, children: [_jsx(BookOpen, { className: "w-3.5 h-3.5" }), "Courses (", courses.length, ")"] })] })] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "text-xs font-mono text-gray-500 uppercase", children: ["SHOWING ", activeSubTab === 'batches' ? `${batches.length} BATCH COHORTS` : `${courses.length} ACTIVE COURSES`] }), _jsxs("div", { children: [activeSubTab === 'batches' && userRole === 'admin' && (_jsxs("button", { onClick: onOpenAddBatchModal, className: "text-xs bg-white text-black px-4 py-2 font-black uppercase tracking-wider hover:bg-gray-200 transition-colors rounded-sm flex items-center gap-2", children: [_jsx(Plus, { className: "w-4 h-4" }), "Create Batch Cohort"] })), activeSubTab === 'courses' && (_jsxs("button", { onClick: onOpenAddCourseModal, className: "text-xs bg-white text-black px-4 py-2 font-black uppercase tracking-wider hover:bg-gray-200 transition-colors rounded-sm flex items-center gap-2", children: [_jsx(Plus, { className: "w-4 h-4" }), "Add Course to Catalog"] }))] })] }), activeSubTab === 'batches' && (_jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6", children: batches.map((batch) => (_jsxs("div", { className: "bg-[#0F0F0F] border border-[#222222] rounded-sm p-6 space-y-4 hover:border-white transition-all relative", children: [_jsxs("div", { className: "flex items-start justify-between gap-3", children: [_jsxs("div", { children: [_jsx("span", { className: "text-[10px] font-mono font-bold uppercase tracking-wider text-black bg-white px-2 py-0.5", children: batch.code }), _jsx("h3", { className: "font-bold text-white text-lg mt-3", children: batch.name }), _jsx("p", { className: "text-xs font-mono text-gray-500 uppercase", children: batch.department })] }), _jsx("span", { className: `px-2 py-0.5 rounded-sm text-[9px] font-mono font-bold uppercase ${batch.status === 'active'
                                        ? 'bg-green-500/10 text-green-400 border border-green-500/30'
                                        : 'bg-[#222222] text-gray-400 border border-[#333333]'}`, children: batch.status })] }), _jsxs("div", { className: "grid grid-cols-2 gap-3 p-3 bg-[#181818] border border-[#222222] rounded-sm text-xs font-mono", children: [_jsxs("div", { children: [_jsx("span", { className: "text-[9px] text-gray-500 uppercase font-bold block", children: "ENROLLED" }), _jsxs("div", { className: "font-bold text-white flex items-center gap-1.5 mt-0.5", children: [_jsx(Users, { className: "w-3.5 h-3.5 text-white" }), batch.studentCount || 0, " Students"] })] }), _jsxs("div", { children: [_jsx("span", { className: "text-[9px] text-gray-500 uppercase font-bold block", children: "ACADEMIC STAGE" }), _jsxs("div", { className: "font-bold text-white mt-0.5", children: ["YR ", batch.year, " \u2022 SEM ", batch.semester] })] })] }), _jsxs("div", { className: "text-xs font-mono text-gray-400 flex items-center gap-2", children: [_jsx(UserCheck, { className: "w-3.5 h-3.5 text-gray-500 shrink-0" }), _jsxs("span", { children: ["ADVISOR: ", _jsx("strong", { className: "text-white font-bold", children: batch.advisorName || 'UNASSIGNED' })] })] }), userRole === 'admin' && (_jsx("div", { className: "pt-3 border-t border-[#222222] flex justify-end", children: _jsxs("button", { onClick: () => onDeleteBatch(batch.id), className: "text-[10px] font-mono text-gray-500 hover:text-red-400 transition-colors uppercase font-bold flex items-center gap-1", children: [_jsx(Trash2, { className: "w-3.5 h-3.5" }), " Delete Cohort"] }) }))] }, batch.id))) })), activeSubTab === 'courses' && (_jsx("div", { className: "bg-[#0F0F0F] border border-[#222222] rounded-sm overflow-hidden", children: _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "w-full text-left text-xs text-gray-300 font-mono", children: [_jsx("thead", { className: "bg-[#181818] text-gray-400 font-bold border-b border-[#222222] uppercase tracking-wider text-[10px]", children: _jsxs("tr", { children: [_jsx("th", { className: "py-3 px-4", children: "Course Code" }), _jsx("th", { className: "py-3 px-4", children: "Course Title" }), _jsx("th", { className: "py-3 px-4", children: "Department" }), _jsx("th", { className: "py-3 px-4", children: "Credits" }), _jsx("th", { className: "py-3 px-4", children: "Faculty Assigned" }), _jsx("th", { className: "py-3 px-4", children: "Target Cohort" })] }) }), _jsx("tbody", { className: "divide-y divide-[#181818]", children: courses.map((crs) => {
                                    const targetBatch = batches.find(b => b.id === crs.batchId);
                                    return (_jsxs("tr", { className: "hover:bg-[#181818] transition-colors", children: [_jsx("td", { className: "py-3.5 px-4 font-mono font-bold text-white", children: crs.code }), _jsx("td", { className: "py-3.5 px-4 font-bold text-white font-sans", children: crs.name }), _jsx("td", { className: "py-3.5 px-4 text-gray-400 uppercase", children: crs.department }), _jsx("td", { className: "py-3.5 px-4", children: _jsxs("span", { className: "px-2 py-0.5 bg-[#222] text-white border border-[#333] font-mono font-bold text-[10px]", children: [crs.credits, " CREDITS"] }) }), _jsx("td", { className: "py-3.5 px-4 text-white font-sans font-bold", children: crs.facultyName }), _jsx("td", { className: "py-3.5 px-4 text-gray-400", children: targetBatch ? targetBatch.code : 'ALL BATCHES' })] }, crs.id));
                                }) })] }) }) }))] }));
};
