import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { ShieldCheck, UserCheck, Search } from 'lucide-react';
export const Navbar = ({ currentUser, allUsers, onSwitchUser, searchQuery, onSearchChange }) => {
    const displayUsers = allUsers.filter((u, index, self) => index === self.findIndex((x) => x.role === u.role));
    return (_jsx("header", { className: "sticky top-0 z-30 bg-[#0F0F0F] border-b border-[#222222] text-[#F0F0F0]", children: _jsxs("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between gap-4", children: [_jsxs("div", { className: "flex items-center gap-3 shrink-0", children: [_jsx("div", { className: "w-8 h-8 bg-[#2563EB] text-white flex items-center justify-center rounded-sm shrink-0 font-black text-xs", children: "YM" }), _jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("h1", { className: "text-xl font-bold tracking-tight text-white", children: "youthmatrix" }), _jsx("span", { className: "text-[10px] bg-[#222222] px-2 py-0.5 border border-[#333333] font-mono text-gray-400", children: currentUser.role.toUpperCase() })] }), _jsx("p", { className: "text-[10px] text-gray-500 uppercase tracking-widest font-bold mt-0.5", children: "Student Management System" })] })] }), _jsx("div", { className: "hidden md:flex flex-1 max-w-md mx-4", children: _jsxs("div", { className: "relative w-full", children: [_jsx(Search, { className: "w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-gray-500" }), _jsx("input", { type: "text", value: searchQuery, onChange: (e) => onSearchChange(e.target.value), placeholder: "Search students, roll no, or batches...", className: "w-full pl-9 pr-4 py-1.5 text-xs bg-[#181818] border border-[#333333] font-mono text-[#F0F0F0] placeholder-gray-600 focus:outline-none focus:border-white transition-colors rounded-sm uppercase" }), searchQuery && (_jsx("button", { onClick: () => onSearchChange(''), className: "absolute right-2.5 top-1/2 -translate-y-1/2 text-[10px] text-gray-400 hover:text-white font-mono uppercase", children: "Clear" }))] }) }), _jsxs("div", { className: "flex items-center gap-4 shrink-0", children: [_jsxs("div", { className: "flex items-center gap-2 bg-[#181818] border border-[#222222] rounded-sm p-1", children: [_jsx("span", { className: "text-[10px] text-gray-500 uppercase tracking-widest font-bold hidden sm:inline pl-1", children: "ROLE:" }), _jsx("div", { className: "flex items-center gap-1", children: displayUsers.map((u) => {
                                        const isActive = currentUser.role === u.role;
                                        return (_jsxs("button", { onClick: () => onSwitchUser(u), title: `Switch to ${u.name} (${u.role.toUpperCase()})`, className: `flex items-center gap-1.5 px-2.5 py-1 rounded-sm text-[10px] font-bold tracking-wider uppercase transition-all ${isActive
                                                ? 'bg-white text-black font-black'
                                                : 'text-gray-400 hover:text-white hover:bg-[#222222]'}`, children: [u.role === 'admin' ? (_jsx(ShieldCheck, { className: "w-3.5 h-3.5" })) : (_jsx(UserCheck, { className: "w-3.5 h-3.5" })), _jsx("span", { children: u.role })] }, u.id));
                                    }) })] }), _jsxs("div", { className: "hidden lg:flex flex-col text-right", children: [_jsx("p", { className: "text-[10px] uppercase tracking-widest text-gray-500 font-bold", children: "Session Active" }), _jsx("p", { className: "text-xs font-mono text-white", children: currentUser.name })] })] })] }) }));
};
