import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { X, FileText, AlertTriangle, CheckCircle2, Target, ShieldCheck, Loader2 } from 'lucide-react';
export const PerformanceReportModal = ({ isOpen, onClose, student, reportData, loading }) => {
    if (!isOpen || !student)
        return null;
    return (_jsx("div", { className: "fixed inset-0 z-50 bg-black/80 backdrop-blur-xs flex items-center justify-center p-4", children: _jsxs("div", { className: "bg-[#0F0F0F] border border-[#222222] rounded-sm max-w-2xl w-full p-6 shadow-2xl relative text-white space-y-5", children: [_jsxs("div", { className: "flex items-center justify-between pb-3 border-b border-[#222222]", children: [_jsxs("div", { className: "flex items-center gap-2.5", children: [_jsx("div", { className: "w-8 h-8 rounded-sm bg-white text-black flex items-center justify-center font-black", children: _jsx(FileText, { className: "w-4 h-4" }) }), _jsxs("div", { children: [_jsx("h3", { className: "text-base font-black italic uppercase tracking-wider text-white", children: "Student Performance Report" }), _jsxs("p", { className: "text-xs font-mono text-gray-500 uppercase", children: ["Generated for ", _jsxs("strong", { className: "text-white", children: [student.firstName, " ", student.lastName] }), " (", student.rollNumber, ")"] })] })] }), _jsx("button", { onClick: onClose, className: "p-1 text-gray-400 hover:text-white hover:bg-[#222222] transition-colors rounded-sm", children: _jsx(X, { className: "w-5 h-5" }) })] }), loading ? (_jsxs("div", { className: "p-12 text-center space-y-3 font-mono", children: [_jsx(Loader2, { className: "w-8 h-8 text-white animate-spin mx-auto" }), _jsx("p", { className: "text-xs text-gray-400 font-bold uppercase tracking-wider", children: "Preparing the student performance report..." })] })) : reportData ? (_jsxs("div", { className: "space-y-4 text-xs font-mono", children: [_jsxs("div", { className: `p-3.5 rounded-sm border flex items-center justify-between uppercase ${reportData.overallAcademicRisk === 'High'
                                ? 'bg-red-950/20 border-red-500/40 text-red-400'
                                : reportData.overallAcademicRisk === 'Moderate'
                                    ? 'bg-yellow-950/20 border-yellow-500/40 text-yellow-300'
                                    : 'bg-white/10 border-white/20 text-white'}`, children: [_jsxs("div", { className: "flex items-center gap-2", children: [reportData.overallAcademicRisk === 'Low' ? (_jsx(ShieldCheck, { className: "w-5 h-5" })) : (_jsx(AlertTriangle, { className: "w-5 h-5" })), _jsx("span", { className: "font-bold", children: "Academic Standing Risk Assessment" })] }), _jsxs("span", { className: "font-black uppercase tracking-wider px-2.5 py-0.5 rounded-sm text-[10px] bg-white text-black", children: [reportData.overallAcademicRisk, " Risk"] })] }), _jsxs("div", { className: "p-3.5 bg-[#181818] rounded-sm border border-[#222222] space-y-1 font-sans", children: [_jsx("h4", { className: "font-bold font-mono text-xs uppercase text-gray-400", children: "Executive Performance Summary" }), _jsx("p", { className: "text-gray-200 leading-relaxed text-xs", children: reportData.performanceSummary })] }), _jsxs("div", { className: "grid grid-cols-1 sm:grid-cols-2 gap-3", children: [_jsxs("div", { className: "p-3.5 bg-[#181818] border border-[#222222] rounded-sm space-y-2", children: [_jsxs("h5", { className: "font-bold text-white flex items-center gap-1.5 uppercase text-[11px]", children: [_jsx(CheckCircle2, { className: "w-4 h-4 text-emerald-400" }), " Core Academic Strengths"] }), _jsx("ul", { className: "space-y-1 text-gray-300 list-disc list-inside font-sans text-xs", children: reportData.strengths?.map((str, i) => (_jsx("li", { children: str }, i))) })] }), _jsxs("div", { className: "p-3.5 bg-[#181818] border border-[#222222] rounded-sm space-y-2", children: [_jsxs("h5", { className: "font-bold text-white flex items-center gap-1.5 uppercase text-[11px]", children: [_jsx(AlertTriangle, { className: "w-4 h-4 text-amber-400" }), " Focus & Risk Factors"] }), _jsx("ul", { className: "space-y-1 text-gray-300 list-disc list-inside font-sans text-xs", children: reportData.areasForImprovement?.map((area, i) => (_jsx("li", { children: area }, i))) })] })] }), _jsxs("div", { className: "p-3.5 bg-[#181818] border border-[#333333] rounded-sm space-y-2", children: [_jsxs("h5", { className: "font-bold text-white flex items-center gap-1.5 uppercase text-[11px]", children: [_jsx(Target, { className: "w-4 h-4 text-white" }), " Recommended Faculty Action Plan"] }), _jsx("ol", { className: "space-y-1.5 text-gray-200 list-decimal list-inside font-sans text-xs", children: reportData.recommendedInterventions?.map((step, i) => (_jsx("li", { className: "leading-relaxed", children: step }, i))) })] })] })) : (_jsx("p", { className: "text-xs text-gray-500 font-mono uppercase text-center py-6", children: "Failed to load report." })), _jsx("div", { className: "flex justify-end pt-2 border-t border-[#222222]", children: _jsx("button", { onClick: onClose, className: "px-5 py-2 bg-white text-black hover:bg-gray-200 text-xs font-black uppercase tracking-wider rounded-sm transition-colors", children: "Close Report" }) })] }) }));
};
